### ISSUE TITLE
Header file not found / missing?

### ISSUE THREAD

**Issue by henrygab** [CollinCunningham/BLE_UART_Controller_Test#2]
Where would the header file "Adafruit_BLE_UART.H" be found?

I've installed the Adafruit nRF52 BSP v0.9.3 from https://www.adafruit.com/package_adafruit_index.json.

I then selected board "Adafruit nRF52840 Feather Express".

When attempting to compile this, the header is not found.

**Comment by TiberiusB** [comment]
I had the same problem: 
  -> candidates: [Adafruit BLEFirmata@1.1.2]
/tmp/.arduinoIDE-unsaved2024720-207046-8bobqc.86x4p/StandardFirmata/StandardFirmata.ino:35:10: fatal error: Adafruit_BLE_UART.h: No such file or directory
 #include "Adafruit_BLE_UART.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/messeru/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega32u4 -DF_CPU=8000000L -DARDUINO=10607 -DARDUINO_AVR_FEATHER32U4 -DARDUINO_ARCH_AVR -DUSB_VID=0x239A -DUSB_PID=0x800C -DUSB_MANUFACTURER="Adafruit" -DUSB_PRODUCT="Feather 32u4" -I/home/messeru/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/messeru/.arduino15/packages/adafruit/hardware/avr/1.4.15/variants/feather32u4 -I/home/messeru/.arduino15/libraries/Servo/src -I/home/messeru/.arduino15/packages/adafruit/hardware/avr/1.4.15/libraries/Wire -I/home/messeru/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src -I/home/messeru/Arduino/libraries/Adafruit_BLEFirmata /tmp/arduino/sketches/7798CD7308A9B2DC7FFDD07D5D623882/sketch/StandardFirmata.ino.cpp -o /dev/null
Alternatives for Adafruit_BLE_UART.h: []
ResolveLibrary(Adafruit_BLE_UART.h)
  -> candidates: []
exit status 1

Compilation error: Adafruit_BLE_UART.h: No such file or directory
